backend:
  name: github
  repo: EcoMadeirinha/AlgarveHomeService
  branch: main

media_folder: src/images/uploads
public_folder: ../images/uploads

collections:
  - name: blog
    label: Blog
    folder: src/markdown-pages
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - {
          label: 'Slug',
          name: 'slug',
          widget: 'string',
          hint: 'Always use: /blog/page-name  No spaces between. For ex: /blog/sports-massage',
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'featured',
          widget: 'image',
          hint: 'Only files *.WEBP , to convert your image go to the : https://squoosh.app/ ',
        }
      - { label: 'Description', name: 'excerpt' }
      - { label: 'Tags', name: 'tags', widget: 'list', hint: 'Separate by comma' }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'About Page'
        name: 'about'
        file: 'src/mock/about.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: Photo, name: photo, widget: image }
      - label: 'Hero Section'
        name: 'hero'
        file: 'src/mock/hero.json'
        fields:
          - { label: OverTitle, name: overTitle, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: AfterTitle, name: afterTitle, widget: string }
          - { label: ButtonOne, name: buttonOne, widget: string }
          - { label: ButtonTwo, name: buttonTwo, widget: string }
      - label: 'Presentation Section'
        name: 'presentation'
        file: 'src/mock/presentation.json'
        fields:
          - lable: block_One
            name: 'block_One'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Message, name: message, widget: string }
              - { label: Image, name: image, widget: image }
              - { label: Image_Description, name: image_Description, widget: string }
              - { label: Button, name: button, widget: string }
          - lable: block_Two
            name: 'block_Two'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Message, name: message, widget: string }
              - { label: Image, name: image, widget: image }
              - { label: Image_Description, name: image_Description, widget: string }
              - { label: Button, name: button, widget: string }
          - lable: block_Three
            name: 'block_Three'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Message, name: message, widget: string }
              - { label: Image, name: image, widget: image }
              - { label: Image_Description, name: image_Description, widget: string }
              - { label: Button, name: button, widget: string }
      - label: 'Service Section'
        name: 'service'
        file: 'src/mock/service.json'
        fields:
          - lable: block_One
            name: 'block_One'
            widget: object
            fields:
              - { label: Over_Title, name: over_Title, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Image, name: image, widget: image }
              - { label: Image_Description, name: alt, widget: string }
              - { label: Price_From, name: price_From, widget: string }
              - { label: Link_to, name: link_to, widget: string }
          - lable: block_Two
            name: 'block_Two'
            widget: object
            fields:
              - { label: Over_Title, name: over_Title, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Image, name: image, widget: image }
              - { label: Image_Description, name: alt, widget: string }
              - { label: Price_From, name: price_From, widget: string }
              - { label: Link_to, name: link_to, widget: string }
          - lable: block_Three
            name: 'block_Three'
            widget: object
            fields:
              - { label: Over_Title, name: over_Title, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Image, name: image, widget: image }
              - { label: Image_Description, name: alt, widget: string }
              - { label: Price_From, name: price_From, widget: string }
              - { label: Link_to, name: link_to, widget: string }
          - lable: block_Four
            name: 'block_Four'
            widget: object
            fields:
              - { label: Over_Title, name: over_Title, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Image, name: image, widget: image }
              - { label: Image_Description, name: alt, widget: string }
              - { label: Price_From, name: price_From, widget: string }
              - { label: Link_to, name: link_to, widget: string }
